/* ===================================
   CASE011 - Notebook System
   Interactive note-taking with auto-save
   =================================== */

let notebookAutoSaveInterval;
let currentCaseHash;

/**
 * Initialize notebook for a case
 * @param {string} caseHash - Case hash
 */
function initNotebook(caseHash) {
    currentCaseHash = caseHash;
    const notebookArea = document.getElementById('notebookArea');
    const timestampBtn = document.getElementById('timestampBtn');
    const clearBtn = document.getElementById('clearBtn');
    const saveIndicator = document.getElementById('saveIndicator');
    const wordCount = document.getElementById('wordCount');
    const charCount = document.getElementById('charCount');

    // Load saved notebook
    const savedNotebook = loadNotebook(caseHash);
    if (savedNotebook) {
        notebookArea.value = savedNotebook;
        updateStats();
    }

    // Auto-save every 30 seconds
    notebookAutoSaveInterval = setInterval(() => {
        saveNotebook(caseHash, notebookArea.value);
        showSaveIndicator(saveIndicator);
    }, 30000);

    // Save on input (debounced)
    const debouncedSave = debounce(() => {
        saveNotebook(caseHash, notebookArea.value);
        showSaveIndicator(saveIndicator);
    }, 2000);

    notebookArea.addEventListener('input', () => {
        updateStats();
        debouncedSave();
    });

    // Timestamp button
    if (timestampBtn) {
        timestampBtn.addEventListener('click', () => {
            insertTimestamp(notebookArea);
        });
    }

    // Clear button
    if (clearBtn) {
        clearBtn.addEventListener('click', () => {
            if (confirm('Are you sure you want to clear all notes? This cannot be undone.')) {
                notebookArea.value = '';
                updateStats();
                saveNotebook(caseHash, '');
            }
        });
    }

    // Update word and character count
    function updateStats() {
        const text = notebookArea.value;
        const words = countWords(text);
        const chars = text.length;

        if (wordCount) wordCount.textContent = `${words} words`;
        if (charCount) charCount.textContent = `${chars} characters`;
    }

    // Save before leaving page
    window.addEventListener('beforeunload', () => {
        saveNotebook(caseHash, notebookArea.value);
        clearInterval(notebookAutoSaveInterval);
    });
}

/**
 * Save notebook to localStorage
 * @param {string} caseHash - Case hash
 * @param {string} content - Notebook content
 */
function saveNotebook(caseHash, content) {
    try {
        localStorage.setItem(`case_notebook_${caseHash}`, content);
        localStorage.setItem(`case_notebook_${caseHash}_timestamp`, new Date().toISOString());
        return true;
    } catch (error) {
        console.error('Failed to save notebook:', error);
        return false;
    }
}

/**
 * Load notebook from localStorage
 * @param {string} caseHash - Case hash
 * @returns {string} Notebook content
 */
function loadNotebook(caseHash) {
    try {
        return localStorage.getItem(`case_notebook_${caseHash}`) || '';
    } catch (error) {
        console.error('Failed to load notebook:', error);
        return '';
    }
}

/**
 * Insert timestamp at cursor position
 * @param {HTMLTextAreaElement} textarea - Textarea element
 */
function insertTimestamp(textarea) {
    const timestamp = generateTimestamp();
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value;

    const before = text.substring(0, start);
    const after = text.substring(end);

    textarea.value = before + timestamp + ' ' + after;
    textarea.selectionStart = textarea.selectionEnd = start + timestamp.length + 1;
    textarea.focus();

    // Trigger input event to update stats and save
    textarea.dispatchEvent(new Event('input'));
}

/**
 * Show save indicator
 * @param {HTMLElement} indicator - Indicator element
 */
function showSaveIndicator(indicator) {
    if (!indicator) return;

    indicator.textContent = 'Saving...';
    indicator.style.color = 'var(--color-accent-amber)';

    setTimeout(() => {
        indicator.textContent = 'Auto-saved';
        indicator.style.color = 'var(--color-text-muted)';
    }, 1000);
}

/**
 * Export notebook as text file
 * @param {string} caseHash - Case hash
 */
function exportNotebook(caseHash) {
    const content = loadNotebook(caseHash);
    const caseData = generateCase(caseHash);

    const exportContent = `
CASE011 INVESTIGATION NOTES
===========================

Case: ${caseData.title}
Hash: #${caseHash}
Category: ${caseData.category.toUpperCase()}
Exported: ${formatDate(new Date())}

NOTES
-----

${content}

===========================
Generated by Case011
    `.trim();

    const blob = new Blob([exportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `case011_${caseHash}_notes.txt`;
    a.click();
    URL.revokeObjectURL(url);
}

/**
 * Get notebook statistics
 * @param {string} caseHash - Case hash
 * @returns {Object} Statistics
 */
function getNotebookStats(caseHash) {
    const content = loadNotebook(caseHash);
    const timestamp = localStorage.getItem(`case_notebook_${caseHash}_timestamp`);

    return {
        wordCount: countWords(content),
        charCount: content.length,
        lastSaved: timestamp ? new Date(timestamp) : null,
        isEmpty: content.trim().length === 0
    };
}
